/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

plugins {
    `java-library`
    eclipse
}
 
repositories {
	mavenCentral()
}
 
dependencies {

	// https://mvnrepository.com/artifact/org.slf4j/slf4j-api
	implementation("org.slf4j:slf4j-api:2.0.12")
	// https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
	implementation("ch.qos.logback:logback-classic:1.5.0")
}

